server:
  port: 8886
  servlet:
    context-path: /changdao

spring:
  datasource:
    dialect: mysql
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.3.0.16:6240/sddsm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: XvxLFV88PCXH7tTK

mybatis:
  mapper-locations: classpath*:zhny/mapper/*.xml
  #配置模型路径
  type-aliases-package:
  configuration:
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #空值也返回
    call-setters-on-nulls: true